apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: payment-pipeline
description: main application pipeline
serialPipeline:
  stages:
    - targetId: dev
      profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: development cluster
gke:
  cluster: projects/training-387322/locations/asia-southeast1/clusters/autopilot-cluster-training3
---