apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: payment-webhook
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - context: .
      image: payment-webhook
deploy:
  kubectl:
    manifests:
      - k8s/*