apiVersion: v1
kind: Service
metadata:
  name: payment-checkout-external
spec:
  type: LoadBalancer
  selector:
    app: payment-checkout
  ports:
    - name: http
      port: 80
      targetPort: 8080